version: '2'

services:
  web:
    image: mwongka/squirrel-web-docker:latest
    ports:
      - "3010:3010"
    links: 
      - db
      - dbredis
    command: npm start
  db:
    image: mwongka/squirrel-db-docker:latest
    ports: 
      - "8888:8888"
    command: npm start
  dbredis: 
    image: mwongka/squirrel-dbredis-docker:latest
    ports: 
      - "3333:3333"
    links:
      - redis
      - db 
    command: npm start
  redis: 
    image: redis
    ports: 
      - "6379"
